sudo: false
language: node_js
script:
  - curl https://raw.githubusercontent.com/shapesecurity/CLA/master/cla-travis.sh | bash
  - npm run build
  - npm run generate-coverage
  - npm run check-coverage
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs-2"
  - "iojs-3"
matrix:
  allow_failures:
    - node_js: "iojs-3"
