sudo: false
language: node_js
script:
  - curl https://raw.githubusercontent.com/shapesecurity/CLA/master/cla-travis.sh | bash
  - npm run build
  - npm run generate-coverage
  - npm run check-coverage
node_js:
  - "5.3"
matrix:
  allow_failures:
    - node_js: "iojs-3"
